Fix ImportError when gatspy is installed as a dependency
When other packages install gatspy as one of their dependencies
it's not safe to import gatspy during the install phase.
This is because gatspy's own dependencies might not be installed yet,
e.g. astroML.

This change will fix the following error:
    $ pip install .[full]
    Processing /home/alex/src/pandashells
    Requirement already satisfied (use --upgrade to upgrade): numpy in ./lib/python2.7/site-packages (from pandashells==0.1.4)
    Collecting pandas (from pandashells==0.1.4)
      Downloading pandas-0.16.2.tar.gz (4.9MB)
        100% |████████████████████████████████| 4.9MB 122kB/s
    ...
    Collecting gatspy (from pandashells==0.1.4)
      Downloading gatspy-0.2.tar.gz
        Complete output from command python setup.py egg_info:
        Traceback (most recent call last):
          File "<string>", line 20, in <module>
          File "/tmp/pip-build-0s5QDI/gatspy/setup.py", line 21, in <module>
            import gatspy
          File "gatspy/__init__.py", line 7, in <module>
            from . import datasets, periodic
          File "gatspy/datasets/__init__.py", line 13, in <module>
            from .rrlyrae import *
          File "gatspy/datasets/rrlyrae.py", line 15, in <module>
            from astroML.datasets.tools import get_data_home, download_with_progress_bar
        ImportError: No module named astroML.datasets.tools

        ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-0s5QDI/gatspy